### ISSUE TITLE
[Game Logic] Check if Removing Applies when Game Ends

### ISSUE THREAD

**Issue by nathantoannguyen** [nathantoannguyen/KnuckleBones#1]
Ask CC to play and test if removing die is applied when last move of full board occurs.

For example:

5 6 0      |        5 6 **_5_**            
1 6 2      |        1 6 2 
5 6 3      |        5 6 3
-----     ->       -----
4 2 4      |        4 2 4 
0 2 5      |        0 2 4
0 0 4      |        0 0 0

In out current code, Top player places 5 in 3rd row, removes 5 from Bottom's 3rd row, and game ends. However, it may be different in which it does not cancel out, but let's check whenever we can.

**Comment by nathantoannguyen** [comment]
@maithyy

**Comment by maithyy** [comment]
um she uninstalled cult of the lamb to make space for genshin so this will not be possible any time soon or possibly ever

**Comment by nathantoannguyen** [comment]
bruh moment, this is optional anyway

**Comment by maithyy** [comment]
im down to have it so that in game logic, 5 gets removed from bottom 3rd row and the game continues instead of ending. i feel like that makes more sense game logic wise bc it sounds like. a normal game strategy yk like how in cursed 32 game the columns game was like this

**Comment by nathantoannguyen** [comment]
wdym, the game ends because top board is full anyway

**Comment by maithyy** [comment]
oops i read it wrong

**Comment by maithyy** [comment]
https://youtu.be/E6Id8pzH1rs?t=1039
according to this youtube video of sum1 playing knucklebones we did it correctly YAY!!!
